(function(){
'use strict';
const root=document.getElementById('dominoApp'),toastBox=document.getElementById('dominoToast');
const q=new URLSearchParams(location.search),path=location.pathname,code=q.get('code')||'',token=q.get('token')||'';let timer=null;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
function toast(t){toastBox.textContent=t;toastBox.classList.add('show');setTimeout(()=>toastBox.classList.remove('show'),1600)}
function playerId(){const k='pairs-domino-player';let v=localStorage.getItem(k);if(!v){v=crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random();localStorage.setItem(k,v)}return v}
const pid=playerId(),teacherUrl=(c,t)=>location.origin+'/teacher?code='+encodeURIComponent(c)+'&token='+encodeURIComponent(t),joinUrl=()=>location.origin+'/join?code='+encodeURIComponent(code),projectorUrl=()=>location.origin+'/projector?code='+encodeURIComponent(code)+'&token='+encodeURIComponent(token);
async function get(extra={}){let u='/api/domino?code='+encodeURIComponent(code);for(const[k,v]of Object.entries(extra))if(v)u+='&'+encodeURIComponent(k)+'='+encodeURIComponent(v);const r=await fetch(u,{cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||'request');e.code=d.error;throw e}return d}
async function post(body,includeCode=true){const r=await fetch('/api/domino',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(includeCode?{...body,code}:body)});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||'request');e.code=d.error;throw e}return d}
function hero(sub,title='DomiKnow'){return '<section class="hero"><div class="hero-panel"><div class="eyebrow">כשידע ומשחק מתחברים</div><h1>'+esc(title)+'</h1><p>'+esc(sub||'מתאימים, מחברים ובונים יחד שרשרת של ידע.')+'</p></div></section>'}
function homeVisual(){return '<section class="home-visual" aria-label="DomiKnow — כשידע ומשחק מתחברים"><picture><source media="(max-width:760px)" srcset="/domino-home/domino-home-mobile.png"><img src="/domino-home/domino-home-desktop.png" alt="DomiKnow — משחק דומינו כיתתי"></picture><button type="button" class="home-teacher-hotspot" id="homeTeacherStart" aria-label="כניסת מורה"></button></section>'}
function tile(t,compact=false){return '<div class="domino '+(compact?'compact':'')+'"><div class="domino-half"><span class="domino-half-text">'+esc(t.left)+'</span></div><div class="domino-half"><span class="domino-half-text">'+esc(t.right)+'</span></div></div>'}
let fitRaf=0;
function fitDominoText(){
 cancelAnimationFrame(fitRaf);
 fitRaf=requestAnimationFrame(()=>{
  document.querySelectorAll('.domino-half-text').forEach(el=>{
   const box=el.parentElement;
   el.style.fontSize='';
   let size=parseFloat(getComputedStyle(box).fontSize)||14;
   const min=10.5;
   const fits=()=>el.scrollHeight<=Math.max(20,box.clientHeight-14)&&el.scrollWidth<=Math.max(20,box.clientWidth-14);
   while(size>min&&!fits()){size-=.5;el.style.fontSize=size+'px'}
  });
 });
}
new MutationObserver(fitDominoText).observe(root,{childList:true,subtree:true});
window.addEventListener('resize',fitDominoText);
function chainHtml(list){if(!list?.length)return '<div class="waiting">השרשרת עדיין לא התחילה.</div>';return '<div class="chain-board">'+list.map((t,i)=>tile(t,true)+(i<list.length-1?'<span class="connector">‹</span>':'')).join('')+'</div>'}
function progress(n,total){const p=total?Math.round(n/total*100):0;return '<div class="progress"><span style="width:'+p+'%"></span></div><div class="tiny progress-label">'+n+'/'+total+' קוביות</div>'}
function complete(){return '<div class="complete"><strong>השרשרת הושלמה ✓</strong><span>כל ההתאמות התחברו.</span></div>'}
function startPoll(fn){clearInterval(timer);timer=setInterval(fn,1100)}
function parsePairs(text){return text.split(/\n+/).map(x=>{const p=x.split('|');return{left:(p.shift()||'').trim(),right:p.join('|').trim()}}).filter(p=>p.left&&p.right).slice(0,40)}
function renderHome(){
 document.body.classList.remove('projector');const last=localStorage.getItem('pairs-domino-last-teacher')||'';
 root.innerHTML='<div class="shell home-shell">'+homeVisual()+
 '<section class="card create-game-card" id="createGameSection"><h2>יצירת משחק חדש</h2><div class="grid"><div><label class="field"><span>מקצוע</span><input id="subjectName" maxlength="60" placeholder="לדוגמה: ביולוגיה"></label><label class="field"><span>כיתה</span><input id="className" maxlength="60" placeholder="לדוגמה: ח׳2"></label><label class="field"><span>נושא</span><input id="topicName" maxlength="80" placeholder="לדוגמה: מערכת הנשימה"></label><label class="field"><span>מספר זוגות</span><input id="wantedPairs" type="number" min="4" max="40" value="20" inputmode="numeric"></label><label class="field"><span>שם המשחק — לא חובה</span><input id="gameTitle" maxlength="80" placeholder="לדוגמה: נושמים נכון"></label></div><div class="muted">הזינו את פרטי השיעור פעם אחת. המקצוע, הכיתה והנושא ייכנסו אוטומטית לפרומפט.<br><br>את הזוגות מזינים בפורמט:<br><strong>מושג | התאמה</strong></div></div>'+
 '<section class="prompt-helper"><div class="prompt-head"><div><strong>צריכים עזרה ביצירת הזוגות?</strong><span>ערכו את הפרומפט והעתיקו אותו לבינה המועדפת עליכם.</span></div><button class="btn ghost compact-btn" id="copyPrompt">העתקת פרומפט</button></div><textarea id="promptText" class="prompt-text">אני מורה ל__________ ומלמד/ת תלמידי כיתה ________ את הנושא: __________.\nצור עבורי מאגר של 20 זוגות למשחק דומינו לימודי.\n\nכל זוג צריך לכלול:\nמושג קצר | הגדרה / שאלה / תיאור שהתשובה עליו היא בדיוק אותו מושג\n\nהקפד על ניסוח קצר וברור, התאמה לגיל התלמידים, ללא כפילויות, ללא מושגים כמעט זהים, וללא כתיבת המושג עצמו בתוך ההגדרה.\nהמושג צריך להיות קצר ככל האפשר, רצוי עד 22 תווים. ההגדרה/התיאור צריכים להיות תמציתיים, רצוי עד 55 תווים. אם ניתן לקצר בלי לפגוע בדיוק — קצר.\n\nהחזר את התשובה בתוך בלוק קוד רגיל בלבד (plain text), ללא כותרת, ללא מספור, ללא bullets וללא טקסט לפני או אחרי בלוק הקוד.\n\nבתוך בלוק הקוד חייבות להיות בדיוק מספר השורות שביקשתי — שורה אחת לכל זוג.\nכל זוג נכתב בשורה אחת בלבד בפורמט:\nמושג | התאמה\n\nבסיום כל זוג לחץ Enter פעם אחת ועבור לשורה חדשה.\nאסור לכתוב שני זוגות באותה שורה ואסור להמשיך זוג חדש באותה שורה.\n\nדוגמה מדויקת למבנה הפלט בתוך בלוק הקוד:\nמיטוכונדריה | אברון שבו מתבצעת נשימה תאית\nריבוזום | אברון שבו מתבצע תרגום\nDNA | מולקולה הנושאת מידע תורשתי</textarea></section>'+ 
 '<div class="pairs-head"><div><strong>זוגות למשחק</strong><span>העתיקו את המאגר מהבינה. הכפתור למטה יטען אותו וייצור את המשחק.</span></div></div><label class="field pairs-field"><textarea id="pairs" placeholder="מיטוכונדריה | אברון שבו מתבצעת נשימה תאית\nריבוזום | אברון שבו מתבצע תרגום\nDNA | מולקולה הנושאת מידע תורשתי\n..."></textarea></label>'+
 '<div class="pair-help"><span class="count" id="pairCount">0 זוגות</span><span class="tiny">מינימום 4 · מקסימום 40 זוגות</span></div><div class="btns"><button class="btn pri combo-create" id="createGame">טעינת המאגר ויצירת משחק</button>'+(last?'<button class="btn ghost" id="resumeLast">חזרה למשחק האחרון</button>':'')+'</div><div id="homeFeedback" class="feedback"></div></section>'+
 '<section class="card how"><div><strong>1</strong><span>המורה מזין זוגות</span></div><div><strong>2</strong><span>התלמידים מקבלים קוביות</span></div><div><strong>3</strong><span>הכיתה בונה שרשרת</span></div></section></div>';
 const ta=document.getElementById('pairs'),count=document.getElementById('pairCount'),btn=document.getElementById('createGame'),copyPrompt=document.getElementById('copyPrompt'),promptText=document.getElementById('promptText'),subjectName=document.getElementById('subjectName'),className=document.getElementById('className'),topicName=document.getElementById('topicName'),wantedPairs=document.getElementById('wantedPairs');
 const homeTeacherStart=document.getElementById('homeTeacherStart');if(homeTeacherStart)homeTeacherStart.onclick=()=>document.getElementById('createGameSection')?.scrollIntoView({behavior:'smooth',block:'start'});
 const refresh=()=>{const n=parsePairs(ta.value).length,wanted=Math.max(4,Math.min(40,Number(wantedPairs.value)||20)),missing=Math.max(0,wanted-n);count.textContent=missing? n+' מתוך '+wanted+' זוגות · חסרים '+missing:n+' מתוך '+wanted+' זוגות ✓'};
 const syncPrompt=()=>{const subject=subjectName.value.trim()||'__________',klass=className.value.trim()||'__________',topic=topicName.value.trim()||'__________',wanted=Math.max(4,Math.min(40,Number(wantedPairs.value)||20));const lines=promptText.value.split('\n');lines[0]='אני מורה ל'+subject+' ומלמד/ת תלמידי כיתה '+klass+' את הנושא: '+topic+'.';lines[1]='צור עבורי מאגר של '+wanted+' זוגות למשחק דומינו לימודי.';promptText.value=lines.join('\n')};
 [subjectName,className,topicName].forEach(el=>el.addEventListener('input',syncPrompt));
 wantedPairs.addEventListener('input',()=>{syncPrompt();refresh()});wantedPairs.addEventListener('change',()=>{syncPrompt();refresh()});
 ta.addEventListener('input',refresh);ta.addEventListener('change',refresh);ta.addEventListener('paste',()=>setTimeout(refresh,0));
 syncPrompt();refresh();
 copyPrompt.onclick=async()=>{const t=promptText.value;try{await navigator.clipboard.writeText(t);toast('הפרומפט הועתק')}catch{promptText.select();document.execCommand('copy');toast('הפרומפט הועתק')}};

 btn.onclick=async()=>{const f=document.getElementById('homeFeedback'),wanted=Math.max(4,Math.min(40,Number(wantedPairs.value)||20));btn.disabled=true;f.className='feedback';f.textContent='טוען את המאגר…';try{let t='';try{t=await navigator.clipboard.readText()}catch{}if(t.trim()){t=t.replace(/^\s*\`\`\`(?:text|txt|plaintext)?\s*/i,'').replace(/\s*\`\`\`\s*$/,'').trim();ta.value=t}const pairs=parsePairs(ta.value);refresh();if(pairs.length<wanted){f.className='feedback bad';f.textContent='נמצאו '+pairs.length+' מתוך '+wanted+' זוגות. העתיקו מאגר מלא או הוסיפו זוגות ידנית.';btn.disabled=false;return}f.textContent='יוצר משחק…';const d=await post({action:'create',title:(document.getElementById('gameTitle').value.trim()||topicName.value.trim()),className:className.value.trim(),subject:subjectName.value.trim(),topic:topicName.value.trim(),requestedPairs:wanted,pairs},false);const u=teacherUrl(d.code,d.teacherToken);localStorage.setItem('pairs-domino-last-teacher',u);location.href=u}catch(e){f.className='feedback bad';f.textContent=e.code==='not_enough_pairs'?'אין מספיק זוגות ביחס למספר שבחרת.':'לא ניתן ליצור משחק כרגע.';btn.disabled=false;refresh()}};
 if(last)document.getElementById('resumeLast').onclick=()=>location.href=last;
}
async function renderTeacher(){
 try{const d=await get({teacherToken:token});if(!d.teacher)throw new Error('auth');localStorage.setItem('pairs-domino-last-teacher',location.href);const players=d.players||[],spectators=Math.max(0,players.length-(d.tileCount-1));
 root.innerHTML='<div class="shell">'+hero(d.className?'מסך מורה · '+d.className:'מסך מורה',d.title)+'<section class="card"><div class="teacher-top"><div><div class="status"><span class="dot '+(d.phase==='playing'?'on':'')+'"></span>'+(d.phase==='lobby'?'ממתינים לתלמידים':d.phase==='playing'?'המשחק פעיל':'המשחק הושלם')+'</div><h2>קוד כיתה</h2><div class="code">'+esc(code)+'</div></div><div class="joinbox"><div class="qr"><img alt="QR למשחק" src="/api/qr?text='+encodeURIComponent(joinUrl())+'"></div><div><strong>כניסת תלמידים</strong><div class="linkbox">'+esc(joinUrl())+'</div><div class="btns"><button class="btn ghost" id="copyJoin">העתקת קישור</button><button class="btn ghost" id="openProjector">פתיחת מקרן</button></div></div></div></div></section>'+
 '<div class="grid"><section class="card"><h2>תלמידים מחוברים: '+players.length+'</h2><div class="roster">'+(players.length?players.map(p=>'<span class="chip">'+esc(p.name)+'</span>').join(''):'<span class="muted">עדיין אין תלמידים בלובי.</span>')+'</div>'+(spectators?'<div class="tiny note">'+spectators+' תלמידים יהיו צופים בסבב הזה.</div>':'')+'<div class="btns">'+(d.phase==='lobby'?'<button class="btn pri" id="startGame" '+(!players.length?'disabled':'')+'>התחלת המשחק וחלוקת קוביות</button>':'<button class="btn danger" id="resetGame">איפוס המשחק</button>')+'<button class="btn ghost" id="newRoster">ניקוי תלמידים</button></div></section><section class="card"><h2>מצב השרשרת</h2>'+progress(d.chainCount||0,d.tileCount)+(d.currentClue?'<div class="open-clue"><span>ההתאמה הפתוחה</span>'+esc(d.currentClue)+'</div>':'')+'<div class="tiny note">'+d.pairCount+' זוגות · '+d.tileCount+' קוביות</div></section></div>'+
 '<section class="card"><h2>השרשרת המשותפת</h2>'+chainHtml(d.chain||[])+(d.phase==='complete'?complete():'')+'</section></div>';
 document.getElementById('copyJoin').onclick=async()=>{try{await navigator.clipboard.writeText(joinUrl());toast('הקישור הועתק')}catch{}};
 document.getElementById('openProjector').onclick=()=>window.open(projectorUrl(),'_blank','noopener');
 const s=document.getElementById('startGame');if(s)s.onclick=async()=>{s.disabled=true;try{await post({action:'start',teacherToken:token});renderTeacher()}catch(e){toast(e.code==='no_players'?'אין עדיין תלמידים':'לא ניתן להתחיל');s.disabled=false}};
 const r=document.getElementById('resetGame');if(r)r.onclick=async()=>{if(confirm('לאפס את השרשרת ולחלק מחדש?')){await post({action:'reset',teacherToken:token});renderTeacher()}};
 document.getElementById('newRoster').onclick=async()=>{if(confirm('למחוק את רשימת התלמידים ולפתוח לובי חדש?')){await post({action:'newRoster',teacherToken:token});renderTeacher()}};
 startPoll(async()=>{try{const n=await get({teacherToken:token});if(n.version!==d.version||n.players.length!==players.length)renderTeacher()}catch{}});
 }catch{root.innerHTML='<div class="shell">'+hero()+'<section class="card"><h2>לא ניתן לפתוח את מסך המורה</h2><a class="btn pri linkbtn" href="/">פתיחת משחק חדש</a></section></div>'}
}
async function renderProjector(){
 document.body.classList.add('projector');try{const d=await get({teacherToken:token});if(!d.teacher)throw new Error('auth');
 root.innerHTML='<div class="shell">'+hero(d.className?'תצוגת מקרן · '+d.className:'תצוגת מקרן',d.title)+'<section class="card"><div class="teacher-top"><div><div class="eyebrow">קוד כיתה</div><div class="code">'+esc(code)+'</div></div><div class="joinbox"><div class="qr"><img alt="QR" src="/api/qr?text='+encodeURIComponent(joinUrl())+'"></div><div><strong>'+(d.phase==='lobby'?'סרקו והצטרפו ללובי':d.phase==='playing'?'מי מחזיק את ההתאמה?':'המשחק הסתיים')+'</strong><div class="muted">'+(d.players||[]).length+' תלמידים מחוברים</div></div></div></div>'+(d.currentClue?'<div class="open-clue projector-clue"><span>ההתאמה הפתוחה</span>'+esc(d.currentClue)+'</div>':'')+progress(d.chainCount||0,d.tileCount)+'</section><section class="card">'+chainHtml((d.chain||[]).slice(-5))+(d.lastPlayer?'<div class="feedback ok last-player">✓ '+esc(d.lastPlayer)+' חיבר/ה את הקובייה האחרונה</div>':'')+(d.phase==='complete'?complete():'')+'</section></div>';
 startPoll(async()=>{try{const n=await get({teacherToken:token});if(n.version!==d.version)renderProjector()}catch{}})}catch{root.innerHTML='<div class="shell">'+hero()+'<section class="card"><h2>לא ניתן לפתוח תצוגת מקרן</h2></section></div>'}
}
function joinForm(saved,title='דומינו זוגות'){
 root.innerHTML='<div class="shell student-shell">'+hero('קובייה אחת. התאמה אחת. רגע אחד נכון.',title)+'<section class="card nameform"><h2>כניסה למשחק</h2><p class="muted">כתבו שם פרטי. לאחר שהמורה יתחיל תקבלו קובייה. לחצו כאשר הצד הימני של הקובייה שלכם מתאים להתאמה הפתוחה.</p><input id="playerName" maxlength="24" autocomplete="name" placeholder="השם שלי" value="'+esc(saved||'')+'"><button class="btn pri" id="joinGame">כניסה ללובי</button><div class="feedback" id="joinFeedback"></div></section></div>';
 document.getElementById('joinGame').onclick=async()=>{const name=document.getElementById('playerName').value.trim();if(!name){document.getElementById('joinFeedback').textContent='כתבו שם פרטי.';return}try{await post({action:'join',playerId:pid,name});localStorage.setItem('pairs-domino-name',name);renderStudent()}catch(e){document.getElementById('joinFeedback').textContent=e.code==='game_started'?'המשחק כבר התחיל.':'לא ניתן להצטרף כרגע.'}}
}
async function renderStudent(){
 try{const d=await get({playerId:pid}),saved=localStorage.getItem('pairs-domino-name')||'';if(!d.joined&&d.phase==='lobby'){joinForm(saved,d.title);return}
 if(d.phase==='lobby'){root.innerHTML='<div class="shell student-shell">'+hero('הצטרפת. מחכים שהמורה יתחיל.',d.title)+'<section class="card waiting">את/ה בלובי ✓</section></div>';startPoll(renderStudent);return}
 if(!d.myTile&&d.phase!=='complete'){root.innerHTML='<div class="shell student-shell">'+hero('את/ה צופה בסבב הזה.',d.title)+'<section class="card waiting">אין לך כרגע קובייה. עקבו אחרי השרשרת על המקרן.</section></div>';startPoll(renderStudent);return}
 if(d.phase==='complete'){root.innerHTML='<div class="shell student-shell">'+hero('השרשרת הושלמה!',d.title)+'<section class="card">'+complete()+'</section></div>';return}
 root.innerHTML='<div class="shell student-shell">'+hero('בדקו האם הצד הימני שלכם מתאים למה שפתוח עכשיו.',d.title)+'<section class="card"><div class="open-clue"><span>ההתאמה הפתוחה</span>'+esc(d.currentClue)+'</div><div class="my-tile">'+tile(d.myTile)+'</div><div class="match-action"><button class="btn pri" id="playTile">זה מתאים — חיבור הקובייה</button><div class="feedback" id="playFeedback"></div></div></section></div>';
 document.getElementById('playTile').onclick=async()=>{const b=document.getElementById('playTile'),f=document.getElementById('playFeedback');b.disabled=true;try{const x=await post({action:'play',playerId:pid});if(x.correct){f.className='feedback ok';f.textContent='נכון! הקובייה התחברה ✓';setTimeout(renderStudent,650)}else{f.className='feedback bad';f.textContent='עדיין לא — חפשו התאמה מדויקת.';b.disabled=false}}catch{b.disabled=false}};
 startPoll(async()=>{try{const n=await get({playerId:pid});if(n.version!==d.version)renderStudent()}catch{}});
 }catch{root.innerHTML='<div class="shell student-shell">'+hero()+'<section class="card"><h2>המשחק לא נמצא</h2></section></div>'}
}
if(path.startsWith('/teacher'))renderTeacher();else if(path.startsWith('/projector'))renderProjector();else if(path.startsWith('/join'))renderStudent();else renderHome();
})();